### PR TITLE
Fixed ipv6 counting; should be improved upon!

### PR DESCRIPTION
**Pull request by jovandeginste**
This turned out to be easier than expected (I think)

Can you test this before merging? It seemed to be working for me, but it's late so I'm not sure of anything anymore ;-)

### CODE REVIEW

**Comment by asasfu** [comment]
Looks pretty decent, I'll leave you to test it a bit tomorrow :) I'm not even sure where my firewalld testing VM is at the moment :)........  I like how you handled the commands and iptables method.  Send me a message after some decent testing tomorrow and i'll drop the merge into place if you feel confident.  Otherwise I probably wont get around to spinning up my testbed until later this week.

**Comment by jovandeginste** [comment]
OK I have it planned for tomorrow. I'll also see if I can contribute some glue-classes between hiera and your module... At least, that was what I originally set out to do today :-)

**Comment by jovandeginste** [comment]
Verified to work

**Comment by asasfu** [comment]
Thanks Jo, works with ipv6 and ipv4 rules and services set?

**Comment by jovandeginste** [comment]
Yes

**Comment by asasfu** [comment]
Do you want the same merge message 'should be improved upon' or do you think this is pretty solid?

**Comment by jovandeginste** [comment]
I think there are some improvements to be made in the filter - it is perhaps possible that something is open on ::/0 but not on 0.0.0.0/0 (and thus, more intelligent filtering should be used)

**Pull request merged**
